name: Sign and Notarize Mac terraform
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
jobs:
  sign-and-notarize-mac-cli:
    runs-on: macos-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SHORELINE_BUILD_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.SHORELINE_BUILD_AWS_SEC }}
          aws-region: us-west-2
      - name: Download cli asset
        env:
          version: ${{ github.event.inputs.version }}
        run: |
          aws s3 cp s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_amd64 ./terraform-provider-shoreline_${version}_darwin_amd64
          aws s3 cp s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_arm64 ./terraform-provider-shoreline_${version}_darwin_arm64
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name: Install gon via HomeBrew for code signing and app notarization
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
      - name: Sign and notarize mac x86 cli
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          version: ${{ github.event.inputs.version }}
        run: |
          chmod 755 ./terraform-provider-shoreline_${version}_darwin_amd64
          mv ./terraform-provider-shoreline_${version}_darwin_amd64 ./terraform-provider-shoreline_${version}_darwin_amd64.command
          chmod 755 ./terraform-provider-shoreline_${version}_darwin_amd64.command
          echo '{
            "source" : ["./terraform-provider-shoreline_'"${version}"'_darwin_amd64.command"],
            "bundle_id" : "io.shoreline.terraform",
            "apple_id": {
               "username" : "build@shorelinesoftware.com",
               "password":  "@env:AC_PASSWORD"
            },
            "sign" :{
               "application_identity" : "E4C09D7E61638C54FFD01886C778C5474B9F958D"
            },
            "dmg" :{
               "output_path":  "./terraform-provider-shoreline_'"${version}"'_darwin_amd64.dmg",
               "volume_name":  "terraform-provider-shoreline_'"${version}"'_darwin_amd64.command"
            }
          }' | jq '.' > gon.json
          gon -log-level=debug -log-json ./gon.json
      - name: Sign and notarize mac M1 cli
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          version: ${{ github.event.inputs.version }}
        run: |
          chmod 755 ./terraform-provider-shoreline_${version}_darwin_arm64
          mv ./terraform-provider-shoreline_${version}_darwin_arm64 ./terraform-provider-shoreline_${version}_darwin_arm64.command
          chmod 755 ./terraform-provider-shoreline_${version}_darwin_arm64.command
          echo '{
            "source" : ["./terraform-provider-shoreline_'"${version}"'_darwin_arm64.command"],
            "bundle_id" : "io.shoreline.terraform",
            "apple_id": {
               "username" : "build@shorelinesoftware.com",
               "password":  "@env:AC_PASSWORD"
            },
            "sign" :{
               "application_identity" : "E4C09D7E61638C54FFD01886C778C5474B9F958D"
            },
            "dmg" :{
               "output_path":  "./terraform-provider-shoreline_'"${version}"'_darwin_arm64.dmg",
               "volume_name":  "terraform-provider-shoreline_'"${version}"'_darwin_arm64.command"
            }
          }' | jq '.' > gon.json
          gon -log-level=debug -log-json ./gon.json
      - name: Upload signed cli to S3
        env:
          version: ${{ github.event.inputs.version }}
        run: |
          aws s3 rm s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_amd64
          aws s3 cp ./terraform-provider-shoreline_${version}_darwin_amd64.dmg s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_amd64.dmg
          aws s3 rm s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_arm64
          aws s3 cp ./terraform-provider-shoreline_${version}_darwin_arm64.dmg s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_arm64.dmg
